import GradientText from "../components/gradient/GradientText"
import tango from '../components/projects/images/oldimages/devu/tango.png'
import controlflow from '../components/projects/images/oldimages/devu/controlFlow.png'
import DevuProjectShowcase from "../components/carousel/DevuProjectShowcase"
import homeImg from '../components/projects/images/oldimages/devu/home.png'

function DevU(){

    return (
        <div>
            <div className="h-screen lg:-mt-[200px]  flex  flex-col text-center items-center justify-center  ">
                <div className="text-[80px] -mt-[400px] lg:text-[100px] ">
                    <GradientText
                        colors={["#FFD1BA", "#FF8C42", "#FF6B6B", "#FF5DA2", "#8F5EFF", "#3D348B"]}
                        animationSpeed={4}
                        showBorder={false}
                        className="custom-class"
                    >
                        DevU
                    </GradientText>
                </div>
            
 
            </div>

            <section className="info">
                {/* <div className="mx-auto mt-[100px] w-[400px] lg:w-[800px] text-center"> */}
                <div className="mx-auto -mt-[500px] w-[400px] lg:w-[800px] text-center">
                    <div className="text-[40px]  mx-auto ">What is DevU?</div>
                    <div className="mt-[10px]">{"An open source project designed to grade university students’ coding homework submissions against numerous tests generated by instructors, this project was designed by multiple computer science instructors and other industry consultants to re-create the auto-grading API for the University at Buffalo but can also be used/edited by multiple institutions. As a contributor to the project, I played a role in developing and improving the grading system by assisting in the creation and testing of the courses, assignments, and submissions entities. Autolab, which is pictured above, will eventually be replaced by DevU at UB."}</div>
                </div>

                    <div className="lg:w-[900px] mx-auto mt-[100px] ">
                                <img src={homeImg} />
                    </div>     

                {/* <div className="mt-[60px]  mx-auto w-[900px] text-center"> */}
                <div className="mx-auto  w-[400px] lg:w-[800px] text-center">
                    <div className="mt-[100px] text-[40px] mx-auto ">Overview</div>
                    <div className="mt-[10px] mb-[40px]">{"- AutoLab is a sophisticated course management platform developed by Carnegie Mellon University students and faculty. It offers instructors automated programming assessments and tracks scores via web-based technology. Along with automatic evaluation and score tracking, AutoLab provides a comprehensive set of services, including grading, assignment distribution, code annotation, plagiarism detection, and more."}</div>
                    <div className="mb-[40px]">{"- Our goal was to redesign and enhance the existing version of the AutoLab system utilized by the University at Buffalo for the evaluation of students' programming assignments."}</div>
                    <div>{"- Our team, composed of alumni with experience on the AutoLab system, undertook a comprehensive redevelopment. During the process, I honed my project management and teamwork skills and gained insights into executing real-world programming projects."}</div>
                    <div className="mt-[100px] text-[40px] mx-auto ">Why we want to build a replacement:</div>
                    <div className="mt-[10px] mb-[40px]">{"Autolab faced reliability issues, including poor performance and grading inaccuracies. These led to downtime and incorrect feedback for students, causing classes to reschedule assignments. To prevent future issues, we designed DevU with stability and reliability in mind, reducing the need for unscheduled maintenance and outages. To illustrate the reliability issues faced by Autolab, I have included a graph from the Tango VMs showing the number of job errors and job failures. As you can see from the graph, the rate of errors and failures is small but the number is usually less than 5. However this is still relatively high, leading to the need for a more stable solution. That's why we've built DevU with stability and reliability as our top priority."}</div>
                </div>

                <div className="mx-auto text-center lg:w-[1000px]">
                    <img src={tango} />
                </div>
            </section>  

            <section id="workflow">
                 <div className="mx-auto mt-[100px] w-[400px] lg:w-[800px] text-center">
                    <div className="mt-[20px] font-bold text-[40px]">How the current autolab works:</div>


                    <div className="text-[40px] mx-auto mt-[20px]">AUTOGRADING:</div>
                    <div className="mt-[10px]">{"AutoGrading, a key feature of AutoLab, allows real-time evaluation and grading of student programming assignments in a variety of languages and software packages. This provides immediate feedback and improves the student learning experience compared to traditional methods."}</div>
                    <div className="text-[40px] mx-auto mt-[25px]">SCOREBOARD</div>
                    <div className="mt-[10px]">{"The Scoreboard in AutoLab elevates the student experience with its real-time display of anonymous, autograded scores that foster a sense of community and friendly competition. This dynamic duo of autograding and scoreboard creates an optimal learning atmosphere that inspires students to perform at their best, while keeping them informed and on track."}</div>
                    <div className="text-[40px] mx-auto mt-[25px]">SECURITY</div>
                    <div className="mt-[10px]">{"Tango is a powerful web service that drives the efficiency of Autolab's job management. It provides secure isolation for student code by provisioning Docker containers and reporting results to the Autolab UI. This leads to increased scalability, ensuring that submissions can be processed quickly and efficiently, while minimizing the risk of malware."}</div>
                
                
                

                    <div className="text-[40px] mx-auto mt-[30px]">How DevU works:</div>
                    <div className="mt-[10px] mb-[20px]">{"AutoGrading, a key feature of AutoLab, allows real-time evaluation and grading of student programming assignments in a variety of languages and software packages. This provides immediate feedback and improves the student learning experience compared to traditional methods."}</div>
                    
                    <img src={controlflow}></img>
                </div>
            </section>


            <section id="testing">
                <div className="mx-auto mt-[100px] w-[400px] lg:w-[800px] text-center">
                {/* <div className="mx-auto text-center w-[800px] mt-[20px] "> */}
                    <div className="text-[40px] mx-auto ">My Role:</div>
                    <div className="mt-[10px]">{"In my role on the DevU project, I was tasked with working on various components, including courses, assignments, submissions, the assignments section, and the course sections. At the start, I collaborated with another student specifically on the courses and assignments entities. We utilized a separate branch on Github to share and exchange code. My first task was to familiarize myself with the project structure and make necessary corrections, such as fixing typos. As I gained a better understanding of the code, I became increasingly involved in coding and committing changes. My first entity involved creating controller tests for the courses and assignments entities, which involved handling HTTP requests and verifying their correct handling. Once the work on the courses and assignments entities was finalized and merged with the master branch, I was tasked with completing the Submissions entity on my own."}</div>
                    <div className="text-[40px] mx-auto mt-[20px]">Testing</div>
                    <div className="mt-[10px]">{"For testing there are two types of testing that is required to be conducted. One for the entities individual files like the controller and serializer and testing in Postman for the entity itself. The individual tests required individual testing files, for example the submissions controller file requires a submissions controller test file which uses Jest, a popular testing framework, to verify that the controller behaves correctly in different scenarios. The tests cover four main aspects:"}</div>
                    
                    <div className="mt-[20px] -mb-[10px]">{"Getting all submissions (GET /submissions)"}</div>
                    <div className="mt-[10px] -mb-[10px]">{"Getting a submission by ID (GET /submissions/:id)"}</div>
                    <div className="mt-[10px] -mb-[10px]">{"Creating a new submission (POST /submissions)"}</div>
                    <div className="mt-[10px] ">{"Updating a submission (PUT /submissions/:id)"}</div>
                    
                    <div className="mt-[20px]">{"The second type of testing focuses on the entity as a whole. To accomplish this, I utilized Postman to create and manage assignments and courses data by inputting the required information in the POST request body. I then verified the data's accuracy by utilizing GET requests and edited the data through PUT requests. This testing guarantees that the data is accurately stored and easily accessible in the database. Below are images showcasing the step-by-step process of conducting these tests in Postman."}</div>
                    
                    
                </div>
            </section>


            <section id="projectImages" className="lg:h-[500px]">
                <div className="mx-auto">
                    <DevuProjectShowcase />
                </div>
            </section>
{/* className="text-center h-[400px] w-[800px] mx-auto" */}
            <section id="takeaways" >
                <div className="mx-auto mt-[100px] w-[400px] lg:w-[800px] text-center">
                    <div className="text-[40px] ">Takeaways:</div>
                    <div className="mt-[10px]">{"Working on this project was an incredibly valuable experience for me. I gained a deeper understanding of the specific industry and learned how to effectively use various tools and techniques to tackle challenging problems. The project also allowed me to improve my collaboration and communication skills, as I worked closely with a diverse team of individuals and effectively conveyed my ideas and solutions. Furthermore, I honed my time management skills and learned how to prioritize tasks and manage my workload in a fast-paced environment. Overall, this project was a truly enriching experience that helped me grow both professionally and personally."}</div>
                    <div className="mt-[10px]">{"Explore our project by visiting the "}{<a href="https://github.com/UBAutograding/devU-api">Github Repository!</a>}</div>
                </div>
            </section>

        </div>
    )
}

export default DevU